[general]
newsSource = "/etc/dappswin/news.json"

[gin]
port = 8080
runmode = "dev"
# runmode = "pro"
EnableAdmin = false

[eos]
# TODO 节点池
RPCURL = "https://jungle.eos.dfuse.io"
WalletURL = "unix:///home/xxp/eosio-wallet/keosd.sock"
WalletPW = "PW5KEVCDpGccbv7cpXkoBD5eqESYtKiu4npo5ZmdJg2DpbXR9YMx6"
GameAccount = "xxptoken1234"
ICOAccount = "xiaopingeos2"
# Token合约地址
TokenAccount = "xxptoken1234"
# FromBlkNum = 7529733
FromBlkNum = 9193150

# RPCURL = "https://proxy.eosnode.tools"
# WalletURL = "unix:///root/eosio-wallet/keosd.sock"
# WalletPW = "PW5Jw3kodJVotFzaaUVz7H3KsesTRxwNY761kh1sDEctTcpwf2ubm"
# GameAccount = "cryptogame12"
# TokenAccount = "cryptogame12"
# ICOAccount = "cryptogame11"
# FromBlkNum = 36118039

# 间隔单位（ms）
FetchIdleDur = 500
EnableICO = false
ICOStartTime = 1547352488000
ICOTotalAmount = 60000
ICOFakeAmount = 12000
TokenSymbol = "CGG"
EOS_CGG = 20

# 用户质押锁仓地址
LockAccount = "xiaopingeos4"
# 官方锁仓地址，计算流通数量
OfficialLockAccount = "xxptoken1234"
# CGG发行总量
TotalCGGAmoount = 2e7
UnstakePeriod = "1m"

# 平台利润地址
PlatformAccount = "xiaopingeos4"

[mysql]
host = "127.0.0.1"
port = "3306"
user = "root"
password = "Xiaoping@123456"