[gin]
port = 443
runmode = "dev"
autorender = false
copyrequestbody = true
EnableDocs = true
EnableAdmin = false

[eos]
# TODO 节点池
RPCURL = "https://jungle2.cryptolions.io"
# RPCURL = https://proxy.eosnode.tools
ChainID = "e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473"

# 间隔单位（ms）
FetchIdleDur = 500

# FromBlkNum = 26352774
FromBlkNum = 6815777
GameAccount = "eosplaybrand"

EnableICO = true
ICOAccount = "xiaopingeos2"
ICOStartTime = 1545132825000
ICOTotalAmount = 60000
TokenAccount = "xxptoken1234"
TokenSymbol = "EOS"
EOS_CGG = 20
WalletURL = "unix:///home/xxp/eosio-wallet/keosd.sock"
WalletPW = "PW5KEVCDpGccbv7cpXkoBD5eqESYtKiu4npo5ZmdJg2DpbXR9YMx6"

[mysql]
host = "127.0.0.1"
port = "3306"
user = "root"
password = "Xiaoping@123456"