[gin]
port = 8080
runmode = "dev"
autorender = false
copyrequestbody = true
EnableDocs = true
EnableAdmin = false

[eos]
# TODO 节点池
# RPCURL = https://jungle2.cryptolions.io
RPCURL = "http://47.75.91.111"
ChainID = "e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473"

# 间隔单位（ms）
FetchIdleDur = 500

FromBlkNum = 26352774
GameAccount = "eosplaybrand"
EnableICO = true
ICOAccount = "eosplaybrand"
ICOStartTime = 1545132825000
EOS_CGG = 20

[mysql]
host = "127.0.0.1"
port = "3306"
user = "root"
password = "Xiaoping@123456"