[gin]
port = 8080
runmode = "dev"
# runmode = "pro"
EnableAdmin = false

[eos]
# TODO 节点池
RPCURL = "https://jungle2.cryptolions.io"
WalletURL = "unix:///home/xxp/eosio-wallet/keosd.sock"
WalletPW = "PW5KEVCDpGccbv7cpXkoBD5eqESYtKiu4npo5ZmdJg2DpbXR9YMx6"
GameAccount = "eosplaybrand"
ICOAccount = "xiaopingeos2"
TokenAccount = "xxptoken1234"
FromBlkNum = 7529733

# RPCURL = "https://proxy.eosnode.tools"
# WalletURL = "unix:///root/eosio-wallet/keosd.sock"
# WalletPW = "PW5Jw3kodJVotFzaaUVz7H3KsesTRxwNY761kh1sDEctTcpwf2ubm"
# GameAccount = "cryptogame12"
# TokenAccount = "cryptogame12"
# ICOAccount = "cryptogame11"
# FromBlkNum = 36118039

# 间隔单位（ms）
FetchIdleDur = 500
EnableICO = true
ICOStartTime = 1546769673000
ICOTotalAmount = 60000
TokenSymbol = "CGG"
EOS_CGG = 20

[mysql]
host = "127.0.0.1"
port = "3306"
user = "root"
password = "Xiaoping@123456"